### ISSUE TITLE
.env, config.yaml és a hard kódolt dolgok refaktorizációja.

### ISSUE THREAD

**Issue by Alen1337** [talpramagyarokdc/discord-bot#10]

**Comment by Alen1337** [comment]
> * [ ]  egyelőre "mindenki" (az az 1-2 cog) ad-hoc módon olvassa a config fájlt; ahelyett, hogy mindenki magának nyitogatja, parszolgatja, jó lenne erre egy service, pl. egy külön modul, ami akár memóriában is tarthatja a parszolt adatokat

ez is idetartozik még

**Comment by Alen1337** [comment]
> * [ ]  már a jelenlegi feladatkiírások alapján is lesznek más fájlok is konfigurálásra (pl. RSS); talán megfontolandó, hogy ezeknek a fájloknak egy mappában lenne a helyük valamilyen szisztéma szerint

**Comment by Alen1337** [comment]
https://github.com/talpramagyarokdc/discord-bot/pull/7#issuecomment-2107132872

Ez alapvetően nem egy rossz ötlet, gondolkozok még a megfelelő struktúrán, ha van még tippetek akkor ide jöhetnek az ötletek. @peetya @2colours

**Comment by 2colours** [comment]
Én alapvetően még mindig amondó vagyok, hogy nincs baj a configgal (legfeljebb nincs értelme értékekkel becheckolni, hanem ugyanúgy lehet belőle egy mintafájl, mint a .envnél szokás), és konkrétan különféle funkciók/cogok alapján bontanám az értékeket. Mint ahogy a maga egyszerű módján tettem is a https://github.com/talpramagyarokdc/discord-bot/pull/11 PR-ben.

**Comment by Alen1337** [comment]
Azt a döntést hoztuk ezzel kapcsolatban, hogy a .env-ben tároljuk a Tokent és minden mást a config.yaml-be fogunk tárolni.

Köszi a megértést!
