### ISSUE TITLE
Konvenciók témája

### ISSUE THREAD

**Issue by 2colours** [talpramagyarokdc/discord-bot#19]
Jobb ötletem nem volt, úgyhogy ide tettem.

https://gist.github.com/2colours/906a128ea193b7e89f4c15b9d08b8687

Ez egyelőre nagyon 0.1, van, amit de facto csinálunk, van, amit csak örülnék, ha csinálnánk, van, aminél semmi döntés vagy elképzelés nincsen. Természetesen nem is kell, hogy minden szabványos legyen, de azért jó lenne valami felé konvergálni. Hangsúlyoznám, hogy ez nem egy olyan dolog, amit itt és most kell megoldani meg oltári nagy bikesheddinget csinálni belőle, csak valami olyan, amit érdemes az embernek valahol a feje egy szegletében tartania, hogy kialakuljon szépen.

**Comment by PearooXD** [comment]
Beleraktam a README-be.
