### ISSUE TITLE
BotApp osztály és kivételei

### ISSUE THREAD

**Issue by 2colours** [talpramagyarokdc/discord-bot#6]
Sziasztok,

https://github.com/talpramagyarokdc/discord-bot/blob/5ada1286e9c4b8141adecd2641ab544c930b8876/src/tm_bot.py#L43-L48

első sorban az itt látható részről szólna ez az issue.
Amint elindítottam a botot, ki is dobott az "Application crashed" üzenettel. Ez nem túl segítőkész. Manuálisan beraktam egy traceback dumpot, de ennek amúgy itt semmi értelme: ha kivétel van, a bot mindenképpen leáll, szóval miért nem hagyjuk egyszerűen elcrashelni, amiből úgyis jönne egy rendes dump? (Amúgy mint kiderült, az intentek nem voltak bekapcsolva.)

Viszont ha már ott tartunk, hogy ez a `try-except` inkább árt, mint használ, azt is felvethetjük, hogy ez az egész osztály nem kell. Ami bele van írva a konstruktorba, azt inkább a mainbe kéne átvinni.

**Comment by Alen1337** [comment]
> Ezt javitottam ebben a PR-ben: https://github.com/talpramagyarokdc/discord-bot/pull/7/files#diff-04dc757e71d3b008e5312d9ceab4fdcb318754c5def314467f44830932665b33R48

Ez a megoldás jó lesz egyelőre, később majd ezen változtatunk. 

> Sziasztok,
> 
> https://github.com/talpramagyarokdc/discord-bot/blob/5ada1286e9c4b8141adecd2641ab544c930b8876/src/tm_bot.py#L43-L48
> 
> első sorban az itt látható részről szólna ez az issue. Amint elindítottam a botot, ki is dobott az "Application crashed" üzenettel. Ez nem túl segítőkész. Manuálisan beraktam egy traceback dumpot, de ennek amúgy itt semmi értelme: ha kivétel van, a bot mindenképpen leáll, szóval miért nem hagyjuk egyszerűen elcrashelni, amiből úgyis jönne egy rendes dump? (Amúgy mint kiderült, az intentek nem voltak bekapcsolva.)
> 
> Viszont ha már ott tartunk, hogy ez a `try-except` inkább árt, mint használ, azt is felvethetjük, hogy ez az egész osztály nem kell. Ami bele van írva a konstruktorba, azt inkább a mainbe kéne átvinni.

Annyi a kérés, hogy a main az maradjon szimplán az ami eddig is volt, a többi osztályban oldjuk meg majd a hibakezelést, egyelőre @peetya megoldása lesz az amivel dolgozni fogunk, később lesz majd erre egy külön megoldás ami a hibakezeléssel foglalkozik.
