### ISSUE TITLE
config (és kezelése) rendbe tétele

### ISSUE THREAD

**Issue by 2colours** [talpramagyarokdc/discord-bot#8]
- [x] #9
- [ ] #10
- [ ] egyelőre "mindenki" (az az 1-2 cog) ad-hoc módon olvassa a config fájlt; ahelyett, hogy mindenki magának nyitogatja, parszolgatja, jó lenne erre egy service, pl. egy külön modul, ami akár memóriában is tarthatja a parszolt adatokat

**Comment by Alen1337** [comment]
Ezt zárom, itt megy tovább a dolog: https://github.com/talpramagyarokdc/discord-bot/issues/10
